version: "2"

services:
  web:
    build: .
    environment:
      VIRTUAL_HOST: loft.airytail.co
      LETSENCRYPT_HOST: loft.airytail.co
      LETSENCRYPT_EMAIL: addr.for+letsencrypt@gmail.com
      # LETSENCRYPT_TEST: "true"
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy
  mongodb:
    image: mongo:3.0.4
    command: mongod --smallfiles
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - default

volumes:
  mongodb:

networks:
  nginx-proxy:
    external: true
